### ISSUE TITLE
Uninstall Clarification

### ISSUE THREAD

**Issue by diezLa** [PBSK15/PBSK15#12]
Hello,

After a successful run, I want to uninstall the PBSK15 software. Do I uninstall normally through settings, or is there a way to uninstall through the command console? I'm asking because I don't want to mess anything up.

On a brighter note, the website worked perfectly. You should be very proud of yourself :D

Looking forward to hearing your reply,

Thanks.

**Comment by PBSK15** [comment]
Sorry for the fairly late response, but if you look in your app list, and open the PBSK15 folder, there is a program in there called "PBSK15 Uninstaller".

**Comment by diezLa** [comment]
No worries. My response is late as well.

I can't find the PBSK15 folder on my computer. Would it be in the downloads section?

**Comment by PBSK15** [comment]
What I meant is look for the PBSK15 folder in the apps list in the *Start Menu*. Scroll down until you find the PBSK15 folder, click it to open it, and PBSK15 Uninstall should be listed inside/under the folder. If it's there, open it and go through with the process.

**Comment by diezLa** [comment]
I must be slow, I don't know why I didn't check that earlier. Thanks!

I ran the uninstaller but when it asked me if I was 100% sure, I kept typing "Yes" but it was listing my choice as invalid. I then received this after closing and reopening the installer...

![1](https://github.com/user-attachments/assets/2416ed36-b293-4f57-b817-d7e5cb5078e6)

**Comment by diezLa** [comment]
Ignore the previous message. Now the pop-up says this.

![Image](https://github.com/user-attachments/assets/79c0854f-1886-4bfd-924b-09896f0c7435)

**Comment by PBSK15** [comment]
Disable your antivirus for the moment, it's probably flagging it since it's trying to remove program files or something.
