### ISSUE TITLE
Installer Closing before install

### ISSUE THREAD

**Issue by EliottFlapjack** [PBSK15/PBSK15#3]
After I type y to download the file the app just closes and I don't know why.

https://github.com/PBSK15/PBSK15/assets/168051288/62a04e58-ec17-4419-8fd6-9f49aab84754

**Comment by PBSK15** [comment]
I found the issue, and I also found some other issues and added better error handling in the process. I will release the updated installer soon. Sorry that the installer has so many issues.

**Comment by PBSK15** [comment]
Fixed (at least for now) installer released.
