### ISSUE TITLE
Installed, but not opening (no shortcuts can be found)

### ISSUE THREAD

**Issue by diezLa** [PBSK15/PBSK15#6]
For some reason, the PBSK15 app is not opening after installation. No shortcuts can be found according to my computer. When installing, I said yes to both the desktop and taskbar options and nothing appeared in the taskbar. When I would open the app again after installation, the black-screened code (don't know the exact name of what it is called) would appear and acknowledge that PBSK15 has been installed. That was around 2 minutes ago. One time it asked me if I wanted to uninstall PBSK15, to which I said Y, and it said "please make a valid choice."

Now when I try to open PBSK15, this shows up. (I pressed cancel on this because I do not want to mess up my computer)
![installer](https://github.com/PBSK15/PBSK15/assets/168254092/864deac7-eba7-43b2-b5c9-66f3a90165a4)

For clarification purposes, I did not install Git before I installed the PBSK15 file. Git was installed during the process. I also tried to uninstall and reinstall PBSK15, but the uninstaller shortcut cannot be found either. No shortcuts can be found in any files. Going into settings to uninstall it there does not help either.

Below are pictures of what comes up when trying to open anything.
![unin](https://github.com/PBSK15/PBSK15/assets/168254092/1d885d9e-b437-43a9-89c3-9c8c3254c895)
![unin2](https://github.com/PBSK15/PBSK15/assets/168254092/ef9e1d60-b173-4362-ba0d-0642f44f716d)

On a brighter note, thanks for all you guys do. We all appreciate this project!

**Comment by diezLa** [comment]
Also forgot to say that when being prompted to open PBSK15 after installation the first time, nothing happened.

**Comment by PBSK15** [comment]
It clearly didn't download PBSK15 in the first place. Can you go to C:/Program Files (x86)/PBSK15, and tell me what's in that folder? I suspect there's nothing because it either failed or it caught the downloading error but you quickly skipped the alert that it failed to download.

"On a brighter note, thanks for all you guys do. We all appreciate this project!" Glad you do! Although one correction has to be made to that statement: it's only ever been me who's been developing this project.

**Comment by lostmediarocks00** [comment]
Hi, this is Bradley. And I’m having an issue with this as well. When I
installed it on my computer and tried to open it, it showed a white screen
and nothing popped up.. I also tried opening inspect element on it and
tried to refresh the page with inspect element on it, but it showed an 403
Forbidden error.. and one more thing, it showed a security certificate
warning when I opened it for the first time on my computer.. is there
anything I can do to fix this? If so, what should I do?

Sincerely,
Bradley.

**Comment by PBSK15** [comment]
@lostmediarocks00 Can you please send screenshots and/or videos of this issue so I can further understand it?

**Comment by lostmediarocks00** [comment]
Sure, here are the pics.

**Comment by diezLa** [comment]
Sorry about the miswrite, I appreciate you though!

Nothing is in the PBSK15 file, but I don't recall seeing any errors. Maybe I just missed them.
Attached is a screenshot of the command being run, I did multiple versions because I didn't know if the string quotes should be included or not. I blocked out the user name just to be safe.

![command](https://github.com/PBSK15/PBSK15/assets/168254092/e7491483-7558-4e24-b07e-7ea183d4e3f6)

**Comment by PBSK15** [comment]
@diezLa Well, it turns out I made my own rewrite lol, please do "git --version" instead.
@diezLa Also, you most likely did. Can you rerun the installer and go through with the installation process instead?

**Comment by PBSK15** [comment]
@lostmediarocks00 PLEASE open a separate issue for this, and post comments and send the pictures via GitHub and not through email (since I can't see them).

**Comment by lostmediarocks00** [comment]
Ok, I will do that.

**Comment by diezLa** [comment]
Sure, here's what it says!

![rerun](https://github.com/PBSK15/PBSK15/assets/168254092/bd229b43-e63b-4853-985e-1d079817ea1d)

**Comment by PBSK15** [comment]
@diezLa Alright, so Git successfully installed at least. Re-open the installer and go through with the process again, and tell me what happens. If there are any errors, please provide specific details like pictures of the console window.

**Comment by diezLa** [comment]
It's acknowledging that PBSK15 was installed. I think it is uninstalling it, but then again, it said please make a valid choice after I said yes to that. Right now, it seems to be cloning things. Is that supposed to happen?
![1](https://github.com/PBSK15/PBSK15/assets/168254092/106aff89-b83d-43bf-9464-8404434a1232)

**Comment by PBSK15** [comment]
Yes, cloning means it's downloading the repository.

**Comment by PBSK15** [comment]
@diezLa Has it installed?

**Comment by diezLa** [comment]
Still uninstalling the original application lol. It was taking long because it had to compress and receive a lot of objects. Now it's updating files. 

As long as I don't accidentally close the installer, we should be good lol

**Comment by diezLa** [comment]
Update: I think the program realized I'm trying to uninstall and install PBSK15 again. It says the software is downloaded and is currently adding the software to the "app list." I think that will take a while as well.

**Comment by PBSK15** [comment]
@diezLa It was only redownloading the repository in the first place, it wasn't truly uninstalling the original application (at least in that amount of time). Also, no, adding the software to the "app list" (list of apps in Start Menu) won't take a long time. I should be pretty much done at this point.

**Comment by diezLa** [comment]
I don't know when it started, but that's okay. I checked the files again and everything is back in the program files!
I think it will work after everything is finished. Thanks so much for your help!

**Comment by PBSK15** [comment]
@diezLa Thank _you_ for reporting this issue. I just realized why it didn't work the first time. The reason it didn't work is because if a new command is added (like "git"), it won't update in the current console window. To fix this, the installer has to restart itself.

Let me know if it boots correctly!

**Comment by diezLa** [comment]
Still adding PBSK15 to the app list. I'm scared to close the command window because I don't want it to restart lol

And, no problem!

**Comment by PBSK15** [comment]
@diezLa Um, is it _still_ adding?

**Comment by diezLa** [comment]
Not that I know of! I ended up closing the program because I had to do something that required me to close all tabs and windows. The program looks great, however, I cannot go on after making a secret code to make a PBS account lol

**Comment by PBSK15** [comment]
@diezLa Can you provide more details and elaborate further on this (potential) issue? If you do, please make a separate issue

**Comment by diezLa** [comment]
Will do!

**Comment by diezLa** [comment]
@PBSK15 Actually, I got it. It just needed to be created while in a game as opposed to the home screen.

**Comment by PBSK15** [comment]
@diezLa Why? And what game?

**Comment by PBSK15** [comment]
@diezLa Out of curiosity, what game was it?

**Comment by diezLa** [comment]
@PBSK15 Sorry for the late response! It was Wild Kratts, specifically the "Your Room" that allows players to create their character.

**Comment by PBSK15** [comment]
@diezLa Ahhh yes
